CREATE TABLE IF NOT EXISTS earnings_events (
    id BIGSERIAL PRIMARY KEY,
    ticker VARCHAR(16) NOT NULL,
    company_name VARCHAR(255),
    earnings_date DATE NOT NULL,
    report_time VARCHAR(16),
    fiscal_quarter VARCHAR(16),
    fiscal_year INTEGER,
    sector VARCHAR(128),
    industry VARCHAR(128),
    market_cap NUMERIC,
    exchange VARCHAR(32),
    source VARCHAR(64) DEFAULT 'fmp',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ticker, earnings_date)
);

CREATE TABLE IF NOT EXISTS financial_metrics (
    id BIGSERIAL PRIMARY KEY,
    ticker VARCHAR(16) NOT NULL,
    earnings_date DATE NOT NULL,
    eps_actual NUMERIC,
    eps_estimate NUMERIC,
    revenue_actual NUMERIC,
    revenue_estimate NUMERIC,
    gross_margin NUMERIC,
    gross_margin_yoy NUMERIC,
    operating_margin NUMERIC,
    operating_margin_yoy NUMERIC,
    net_margin NUMERIC,
    net_margin_yoy NUMERIC,
    free_cash_flow NUMERIC,
    operating_cash_flow NUMERIC,
    forward_revenue_guidance NUMERIC,
    forward_eps_guidance NUMERIC,
    debt_to_equity NUMERIC,
    cash_and_equivalents NUMERIC,
    buyback_amount NUMERIC,
    transcript_sentiment NUMERIC,
    raw_payload JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ticker, earnings_date)
);

CREATE TABLE IF NOT EXISTS price_features (
    id BIGSERIAL PRIMARY KEY,
    ticker VARCHAR(16) NOT NULL,
    earnings_date DATE NOT NULL,
    price_1d_pre NUMERIC,
    price_5d_pre NUMERIC,
    price_10d_pre NUMERIC,
    price_20d_pre NUMERIC,
    price_60d_pre NUMERIC,
    ret_1d_pre NUMERIC,
    ret_5d_pre NUMERIC,
    ret_10d_pre NUMERIC,
    ret_20d_pre NUMERIC,
    ret_60d_pre NUMERIC,
    atm_iv NUMERIC,
    iv_rank NUMERIC,
    iv_percentile NUMERIC,
    iv_crush_hist NUMERIC,
    expected_move_pct NUMERIC,
    volume_anomaly NUMERIC,
    rsi_14 NUMERIC,
    macd NUMERIC,
    macd_signal NUMERIC,
    bollinger_position NUMERIC,
    dist_52w_high NUMERIC,
    dist_52w_low NUMERIC,
    feature_payload JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ticker, earnings_date)
);

CREATE TABLE IF NOT EXISTS macro_features (
    id BIGSERIAL PRIMARY KEY,
    feature_date DATE NOT NULL UNIQUE,
    vix NUMERIC,
    vix9d NUMERIC,
    vix3m NUMERIC,
    spy_ret_1d NUMERIC,
    spy_ret_5d NUMERIC,
    spy_ret_20d NUMERIC,
    qqq_ret_1d NUMERIC,
    qqq_ret_5d NUMERIC,
    qqq_ret_20d NUMERIC,
    fed_funds_rate NUMERIC,
    yield_10y NUMERIC,
    yield_2y NUMERIC,
    yield_curve_slope NUMERIC,
    cpi_yoy NUMERIC,
    pce_yoy NUMERIC,
    bull_bear_regime INTEGER,
    hyg_lqd_spread NUMERIC,
    sector_relative JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS predictions (
    id BIGSERIAL PRIMARY KEY,
    ticker VARCHAR(16) NOT NULL,
    earnings_date DATE NOT NULL,
    sector VARCHAR(128),
    direction_prob_up NUMERIC,
    direction_prob_flat NUMERIC,
    direction_prob_down NUMERIC,
    confidence_score NUMERIC,
    expected_move_pct NUMERIC,
    expected_move_low NUMERIC,
    expected_move_high NUMERIC,
    convergence_low NUMERIC,
    convergence_high NUMERIC,
    model_version VARCHAR(64),
    feature_completeness NUMERIC,
    warning_flags JSONB,
    key_drivers JSONB,
    similar_cases JSONB,
    feature_snapshot JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ticker, earnings_date)
);

CREATE TABLE IF NOT EXISTS outcomes (
    id BIGSERIAL PRIMARY KEY,
    ticker VARCHAR(16) NOT NULL,
    earnings_date DATE NOT NULL,
    actual_t1_gap_pct NUMERIC,
    actual_t1_close_return NUMERIC,
    actual_t5_return NUMERIC,
    actual_t20_return NUMERIC,
    max_intraday_move NUMERIC,
    gap_direction VARCHAR(8),
    gap_filled BOOLEAN,
    convergence_low NUMERIC,
    convergence_high NUMERIC,
    convergence_range NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ticker, earnings_date)
);

CREATE TABLE IF NOT EXISTS model_performance (
    id BIGSERIAL PRIMARY KEY,
    model_version VARCHAR(64) NOT NULL,
    sector VARCHAR(128) NOT NULL,
    accuracy NUMERIC,
    precision_weighted NUMERIC,
    recall_weighted NUMERIC,
    f1_weighted NUMERIC,
    mae NUMERIC,
    rmse NUMERIC,
    sharpe_ratio NUMERIC,
    confusion_matrix JSONB,
    feature_importance JSONB,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_earnings_events_date ON earnings_events (earnings_date);
CREATE INDEX IF NOT EXISTS idx_predictions_date ON predictions (earnings_date);
CREATE INDEX IF NOT EXISTS idx_outcomes_date ON outcomes (earnings_date);
